path:
  data_path: './data/GTSRB/'
  result_path: results/
  config_path: config/GTSRB/config.yaml

general:
  num_classes: 43

learning:
  train_batch_size: 64
  test_batch_size: 64
  num_workers: 16
  learning_rate: 0.015
  momentum: 0.9
  weight_decay: 0.0005
  decrease_lr_factor: 0.12
  decrease_lr_every: 5
  epochs: 5

distill:
  train_batch_size: 64
  num_workers: 16
  learning_rate: 0.015
  momentum: 0.9
  weight_decay: 0.0005
  decrease_lr_factor: 0.1
  decrease_lr_every: 20
  epochs: 10

attack_learning:
  train_batch_size: 64
  test_batch_size: 256
  num_workers: 16
  learning_rate: 0.0005
  momentum: 0.9
  weight_decay: 0.00001
  decrease_lr_factor: 0.1
  decrease_lr_every: 30
  epochs: 100
